#pragma once

#define SWAP_HANDS_ENABLE

// Home row mods options
#define PERMISSIVE_HOLD_PER_KEY
#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY
// #undef TAPPING_FORCE_HOLD

// Combos
#define COMBO_VARIABLE_LEN
#define COMBO_TERM 20
#define COMBO_TERM_PER_COMBO

// One shot mods
// #define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_TIMEOUT 1000

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
