BOOTLOADER = caterina
LTO_ENABLE = yes

VPATH  +=  keyboards/gboards/
COMBO_ENABLE = yes

NKRO_ENABLE = yes
MOUSEKEY_ENABLE = no 
STENO_ENABLE = yes

RGBLIGHT_ENABLE = no
OLED_DRIVER_ENABLE = no
ENCODER_ENABLE = no
